#home:
#    path: /
#    controller: Siejka\UserBundle\Controller\DefaultController::index

login:
    path: /login
    controller: Siejka\UserBundle\Controller\SecurityController::login
    
logout:
    path: /logout
    controller: Siejka\UserBundle\Controller\SecurityController::logout
    
register:
    path: /register
    controller: Siejka\UserBundle\Controller\RegistrationController::register
    
verify_email:
    path: /verify/email
    controller: Siejka\UserBundle\Controller\RegistrationController::verifyUserEmail
    
forgot_password:
    path: /reset-password
    controller: Siejka\UserBundle\Controller\ResetPasswordController::request
    
forgot_password_check_email:
    path: /reset-password/check-email
    controller: Siejka\UserBundle\Controller\ResetPasswordController::checkEmail
    
forgot_password_reset_password:
    path: /reset-password/reset/{token}
    controller: Siejka\UserBundle\Controller\ResetPasswordController::reset
    defaults:
        token: null
    